// Board definitions for all supported ESP devices
// Each board maps to esptool-compatible chip targets and flash settings

const BOARDS = [
  {
    id:        'esp8266_generic',
    name:      'ESP8266',
    chip:      'ESP8266',
    desc:      'NodeMCU, ESP-01, ESP-12',
    baud:      115200,
    flashMode: 'dio',
    flashFreq: '40m',
    flashSize: 'detect',
    flashAddr: '0x0',
  },
  {
    id:        'wemos_d1_mini',
    name:      'Wemos D1 Mini',
    chip:      'ESP8266',
    desc:      'D1 Mini / D1 Mini Pro',
    baud:      115200,
    flashMode: 'dio',
    flashFreq: '40m',
    flashSize: '4MB',
    flashAddr: '0x0',
  },
  {
    id:        'esp32',
    name:      'ESP32',
    chip:      'ESP32',
    desc:      'DevKit, WROOM, WROVER',
    baud:      921600,
    flashMode: 'dio',
    flashFreq: '40m',
    flashSize: 'detect',
    flashAddr: '0x1000',
  },
  {
    id:        'esp32s2',
    name:      'ESP32-S2',
    chip:      'ESP32-S2',
    desc:      'S2 Mini, Saola',
    baud:      921600,
    flashMode: 'dio',
    flashFreq: '80m',
    flashSize: 'detect',
    flashAddr: '0x1000',
  },
  {
    id:        'esp32s3',
    name:      'ESP32-S3',
    chip:      'ESP32-S3',
    desc:      'S3 DevKit, Feather S3',
    baud:      921600,
    flashMode: 'dio',
    flashFreq: '80m',
    flashSize: 'detect',
    flashAddr: '0x0',
  },
  {
    id:        'esp32c3',
    name:      'ESP32-C3',
    chip:      'ESP32-C3',
    desc:      'Super Mini, RISC-V',
    baud:      921600,
    flashMode: 'dio',
    flashFreq: '80m',
    flashSize: 'detect',
    flashAddr: '0x0',
  },
  {
    id:        'esp32c6',
    name:      'ESP32-C6',
    chip:      'ESP32-C6',
    desc:      'WiFi 6 + BLE 5',
    baud:      921600,
    flashMode: 'dio',
    flashFreq: '80m',
    flashSize: 'detect',
    flashAddr: '0x0',
  },
  {
    id:        'esp32h2',
    name:      'ESP32-H2',
    chip:      'ESP32-H2',
    desc:      'Thread / Zigbee',
    baud:      921600,
    flashMode: 'dio',
    flashFreq: '48m',
    flashSize: 'detect',
    flashAddr: '0x0',
  },
];
